[default]
DB_NAME = "flask"
DB_SCHEMA = "base"
SQLALCHEMY_DATABASE_URI = "@format postgresql+psycopg2://{this.DB_USER}:{this.DB_PASS}@{this.DB_SERV}:{this.DB_PORT}/{this.DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = false

DB_SCHEMA_CREATE = "@format CREATE SCHEMA IF NOT EXISTS {this.DB_SCHEMA};"
DB_SCHEMA_USE = "@format SET SESSION SEARCH_PATH TO {this.DB_SCHEMA};"


[development]
DB_SERV = "192.168.1.169"
DB_PORT = "5432"
DB_USER = "flask"
DB_PASS = "flask"
