version: '3'

services:

  database:
    image: 'postgres:latest'
    container_name: base_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flask
      POSTGRES_DB: flask
